export const ABOUT_US_PARAGRAPHS = {
    main1: "Searching for Solutions is an educational organization committed to empowering local youth with the tools to develop intellectual curiosity and cultural self-confidence. With digital learning initiatives, our platform aims to support children in their discovery of long-term scholastic interests.",
    main2: "The world today is neither ideal nor fair; However, diverse sources of community education offer us a path towards a more equitable and just world. The values that we know to be essential to the human spirit— education, community, safety, curiosity, independence —are not justly distributed. Our belief is that it should not be an idealized goal, but a realized responsibility to prevent children from struggling under the weight of this injustice."
}

export const MISSION_STATEMENTS = {
    theDream: 'Growing up, scholastic achievement helped to assuage the negative racial bias/perceptions of my peers and served as a positive outlet for a lonely outsider. My commitment to learning made it possible for me to develop an unshakable self-confidence as it was developed in a limitless environment—the brain of my childhood self. And it served me vitally well when I showed up as the new, black kid in school. Upon graduating from college and entering the workforce I found the transition to be eerily similar to those of my childhood schooldays. Lead with your intellectual curiosity, follow up with tenacious work ethic, and then you will be accepted; I  reminded myself.  Once again, the lessons from childhood helped me to navigate and survive.',
    standFor: 'Searching for Solutions is committed to investing in the intellectual growth and development of children from BIPOC communities. It is our mission to provide students with a platform to expand their literary knowledge through readings and conversations that will prioritize their personal and social needs. Our goal is to instill intellectual confidence in our pupils that will help them to better navigate through the education system, as well as the world.',
    ourCommunity: 'Searching for Solutions is a Gen-Z led organization that understands and empathizes with the concerns and issues most relevant to modern-day youth through our own first-hand experiences in scholastic learning environments. Our team is dedicated to creating a network consisting of our community members that will provide an additional layer of academic and emotional support to students.'
}